### ISSUE TITLE
Bisq v1.9.1 released at http://bisq.network

### ISSUE THREAD

**Issue by so7ow** [fflo/docker-bisq#3]
What is the usual timeframe to get an update on the container? I'm assuming it's not advisable to attempt to download/install from the application prompt?

**Comment by fflo** [comment]
As a regular Bisq user I am upgrading this container after checking everything is working as expected using the desktop app on Mac OS X.

**Comment by fflo** [comment]
bisq-on-docker >v1.9.0 published.
