### ISSUE TITLE
DAO state frequently goes out of sync and requires an application shutdown and resync

### ISSUE THREAD

**Issue by so7ow** [fflo/docker-bisq#4]
Any ideas to isolate the cause of this? App works well other than this annoyance.

**Comment by fflo** [comment]
Guess this is a general usage issue of the Bisq application. Occasionally, I have the same issue running Bisq as desktop application. Are you running bisq-on-docker 24-7 or on-demand?

**Comment by so7ow** [comment]
I generally keep bisq-on-docker running 24/7.

I haven't had the DAO sync problem in the few days since the most recent update. Maybe it's resolved somehow. Will keep an eye on it, I guess!

**Comment by fflo** [comment]
@so7ow any update on this case?

**Comment by so7ow** [comment]
Hasn't happened at all over the last few versions. Happy to consider it resolved!
