### ISSUE TITLE
No longer able to RDP to bisq container after tonight's update

### ISSUE THREAD

**Issue by so7ow** [fflo/docker-bisq#5]
Worked fine until today. Now fails. Connecting via Microsoft Remote Desktop app from macOS 12.4. Attached error.
<img width="706" alt="BISQ-DOCKER-NAS" src="https://user-images.githubusercontent.com/633079/172978891-ae689760-d1a4-4270-b46b-fe656457b982.png">

**Comment by fflo** [comment]
Confirm. Seems that re-building the base image using Docker Hub did break something. Working on a fix...

**Comment by so7ow** [comment]
Recommend rolling back to previous version, or got a fix incoming quickly?

**Comment by fflo** [comment]
Rolling back to latest stable version of bisq-on-docker:base and recompiling the packages >v1.9.0 did the trick. Please upgrade to latest or >v1.9.0 to fix this issue.

**Comment by so7ow** [comment]
Confirming fixed for me.
