### ISSUE TITLE
No longer functional since mandatory update released

### ISSUE THREAD

**Issue by so7ow** [fflo/docker-bisq#7]
Bisq release v1.9.8 is apparently mandatory and the older versions are no longer allowed to trade. 

![image](https://user-images.githubusercontent.com/633079/210393659-475ba25e-4141-4ae3-98ea-e5192565029f.jpeg)

**Comment by fflo** [comment]
Thanks for your hint. Fixed.
Published v1.9.8 as :1.9.8, :app and :latest
