### ISSUE TITLE
Bisq v1.9.9 is mandatory as of January 9, 2023

### ISSUE THREAD

**Issue by so7ow** [fflo/docker-bisq#8]

**Comment by so7ow** [comment]
I see an update was released yesterday but it seems to have *removed* Bisq altogether from the container.

**Comment by fflo** [comment]
Thanks. Fixed.
Bisq v1.9.9 new PGP developer signature caused a security related verification failure during automated build process.

**Comment by so7ow** [comment]
Confirming fixed for me.
