### ISSUE TITLE
how to connect?

### ISSUE THREAD

**Issue by michaelsmolka** [fflo/docker-bisq#9]
Hi guys,
sorry for asking this noob question. But could anybody be so kind to point out how i can connect to the app? In the readme i find just the small hint "for remote access using RDP"
Have the container up and running on my NAS, but have absolutely no idea how i could access it from my Mac running MacOS14.7.1?
Tried some RDP Apps but none worked for this. (better said: have no idea how to configure it)
Thank you very much in advance.

**Comment by fflo** [comment]
Hi Michael,

you need to take care to expose the remote desktop client port running the container which defaults to TCP 3389.
After that you can connect to the exposed port using a remote desktop client software. 

Hint: the latest free version from Microsoft for Mac OS has been recently renamed from "Microsoft Remote Desktop" to "Windows App" which sounds quite confusing.

Run "Windows App", upper right "Add", "Add PC":
PC Name: IP address of your NAS
optional: Friendly name for the list
[Add] and open this connection.

**Comment by michaelsmolka** [comment]
Hi,
thank you very very much. Finally it worked.

The bisq app asked for updating. Is it advisable to do this direktly within this setup?

Funny: Have to run a microsoft app on MacOS in order to connect to a Linux OS. 😂
